import type { Exercise } from '../types'

// 动作数据库（Exercise Library 基础版）
// PRIMARY: 主目标肌群；SECONDARY: 辅助肌群；后续可与 3D 肌肉模型关联
export const EXERCISES: Exercise[] = [
  // ===== Chest =====
  {
    id: 'bench-press',
    name: 'Barbell Bench Press',
    nameCn: '杠铃卧推',
    primaryMuscle: 'Chest',
    secondaryMuscles: ['Front Delts', 'Triceps'],
    equipment: 'Barbell / Bench',
    type: 'compound',
    level: 'beginner',
    instructions:
      '仰卧于平板凳，双脚踩实地面。双手略宽于肩抓握杠铃，下放至胸部中段，肘部约45°外展，推起至手臂伸直。',
    tips: '肩胛骨后缩下沉并全程贴凳；杠铃下放轻触胸部；控制离心阶段约2秒。',
    commonErrors: '耸肩/肩胛脱离凳面；下放位置过高(锁喉)；肘部过度外展(90°)。',
    repRange: '4-8 (力量/增肌)',
  },
  {
    id: 'incline-db-press',
    name: 'Incline Dumbbell Press',
    nameCn: '上斜哑铃卧推',
    primaryMuscle: 'Upper Chest',
    secondaryMuscles: ['Front Delts', 'Triceps'],
    equipment: 'Dumbbells / Incline Bench',
    type: 'compound',
    level: 'beginner',
    instructions:
      '调整凳面约30-45°，双手持哑铃于肩部两侧，向上推起至两哑铃靠拢，缓慢下放至胸部上沿。',
    tips: '上斜角度不超过45°避免过多肩部参与；动作轨迹略呈弧线向外展开。',
    commonErrors: '上斜角度过大变成肩推；下放过深导致肩部代偿。',
    repRange: '8-12',
  },
  {
    id: 'chest-press',
    name: 'Machine Chest Press',
    nameCn: '坐姿器械推胸',
    primaryMuscle: 'Chest',
    secondaryMuscles: ['Front Delts', 'Triceps'],
    equipment: 'Machine',
    type: 'machine',
    level: 'beginner',
    instructions: '坐姿调节座椅高度使握把与胸部齐平，向前推起至手臂接近伸直，缓慢还原。',
    tips: '稳定核心，避免身体离开靠背；末端不锁死关节。',
    commonErrors: '借助身体晃动惯性；行程过短。',
    repRange: '10-15',
  },
  {
    id: 'dips',
    name: 'Chest Dips',
    nameCn: '双杠臂屈伸（胸部）',
    primaryMuscle: 'Lower Chest',
    secondaryMuscles: ['Triceps', 'Front Delts'],
    equipment: 'Parallel Bars',
    type: 'compound',
    level: 'intermediate',
    instructions: '双手撑杠，身体前倾，肘部外展下放至肩低于肘，推起回到起始位。',
    tips: '身体前倾更多偏胸部，垂直更多偏三头；控制下放深度避免肩部不适。',
    commonErrors: '动作过深导致肩关节过度伸展；耸肩。',
    repRange: '6-12',
  },
  {
    id: 'cable-fly',
    name: 'Cable Fly',
    nameCn: '绳索夹胸',
    primaryMuscle: 'Chest',
    secondaryMuscles: ['Front Delts'],
    equipment: 'Cable',
    type: 'isolation',
    level: 'beginner',
    instructions:
      '站于龙门架中央，双手持高/中位握把，肘微屈，向前下方夹合至胸前，缓慢打开还原。',
    tips: '全程保持肘部固定角度；感受胸肌收缩；行程充分。',
    commonErrors: '幅度过大肩部前引；肘部随动失去张力。',
    repRange: '12-15',
  },

  // ===== Shoulders =====
  {
    id: 'ohp',
    name: 'Overhead Press',
    nameCn: '站姿杠铃推举',
    primaryMuscle: 'Front Delts',
    secondaryMuscles: ['Side Delts', 'Triceps', 'Upper Chest'],
    equipment: 'Barbell',
    type: 'compound',
    level: 'intermediate',
    instructions:
      '站姿，杠铃置于锁骨前，核心收紧，垂直将杠铃推过头顶至手臂伸直，缓慢下放。',
    tips: '收紧臀部和核心避免腰椎反弓；杠铃路径尽量贴近面部。',
    commonErrors: '腰部过度反弓；下放过低。',
    repRange: '5-8',
  },
  {
    id: 'db-lateral-raise',
    name: 'Dumbbell Lateral Raise',
    nameCn: '哑铃侧平举',
    primaryMuscle: 'Side Delts',
    secondaryMuscles: ['Traps', 'Rear Delts'],
    equipment: 'Dumbbells',
    type: 'isolation',
    level: 'beginner',
    instructions:
      '站姿双手持哑铃于体侧，肘微屈，向两侧抬至与肩同高，稍作停顿缓慢下放。',
    tips: '动作以肩肘带动而非手腕；小重量高次数更佳；避免耸肩借力。',
    commonErrors: '借助惯性甩动；耸肩；抬过高。',
    repRange: '12-20',
  },
  {
    id: 'rear-delt-fly',
    name: 'Rear Delt Fly',
    nameCn: '俯身反向飞鸟',
    primaryMuscle: 'Rear Delts',
    secondaryMuscles: ['Upper Back', 'Traps'],
    equipment: 'Dumbbells',
    type: 'isolation',
    level: 'beginner',
    instructions:
      '俯身屈髋，背平，双手持哑铃自然下垂，向两侧打开至与背齐平，缓慢还原。',
    tips: '保持颈部中立；肩胛不主动后缩，专注肩后束发力。',
    commonErrors: '用背阔/菱形肌代偿；身体晃动。',
    repRange: '12-15',
  },

  // ===== Back =====
  {
    id: 'deadlift',
    name: 'Conventional Deadlift',
    nameCn: '硬拉',
    primaryMuscle: 'Lower Back',
    secondaryMuscles: ['Glutes', 'Hamstrings', 'Traps', 'Forearms', 'Quads'],
    equipment: 'Barbell',
    type: 'compound',
    level: 'intermediate',
    instructions:
      '双脚与髋同宽，杠铃贴近小腿，屈髋屈膝抓握，挺胸收紧背部，伸髋伸膝拉起至站立，还原至地面。',
    tips: '杠铃贴腿上行；保持背部平直；动作由伸髋主导。',
    commonErrors: '弓背；杠铃离身体过远；用腰部而非髋腿发力。',
    repRange: '3-6',
  },
  {
    id: 'lat-pulldown',
    name: 'Lat Pulldown',
    nameCn: '高位下拉',
    primaryMuscle: 'Lats',
    secondaryMuscles: ['Biceps', 'Upper Back'],
    equipment: 'Cable / Machine',
    type: 'compound',
    level: 'beginner',
    instructions:
      '坐姿固定大腿，宽握横杆，胸部微挺，将横杆下拉至上胸，缓慢控制还原。',
    tips: '想象肘部向下向后拉；避免身体大幅后仰借力。',
    commonErrors: '身体过度后仰；只用手臂拉。',
    repRange: '8-12',
  },
  {
    id: 'seated-row',
    name: 'Seated Cable Row',
    nameCn: '坐姿绳索划船',
    primaryMuscle: 'Upper Back',
    secondaryMuscles: ['Lats', 'Biceps', 'Rear Delts'],
    equipment: 'Cable',
    type: 'compound',
    level: 'beginner',
    instructions:
      '坐姿双脚踩稳，挺胸收肩胛，将握把拉向腹部，肘部贴身向后，缓慢还原。',
    tips: '先夹肩胛再拉肘；保持躯干稳定。',
    commonErrors: '身体前后摆动借力；耸肩。',
    repRange: '8-12',
  },
  {
    id: 'single-arm-db-row',
    name: 'One-Arm Dumbbell Row',
    nameCn: '单臂哑铃划船',
    primaryMuscle: 'Lats',
    secondaryMuscles: ['Upper Back', 'Biceps', 'Rear Delts'],
    equipment: 'Dumbbells',
    type: 'compound',
    level: 'beginner',
    instructions:
      '单膝单手撑凳，背部平直，将哑铃提拉至髋部位置，控制下放。',
    tips: '保持躯干稳定不旋转；肘贴近身体向后上方拉。',
    commonErrors: '躯干旋转借力；动作幅度太小。',
    repRange: '8-12',
  },
  {
    id: 'barbell-row',
    name: 'Barbell Row',
    nameCn: '杠铃划船',
    primaryMuscle: 'Upper Back',
    secondaryMuscles: ['Lats', 'Rear Delts', 'Biceps'],
    equipment: 'Barbell',
    type: 'compound',
    level: 'intermediate',
    instructions:
      '屈髋俯身背平，正握杠铃，将杠铃拉向下腹，肩胛后缩，缓慢下放。',
    tips: '保持背部平直避免弓背；肘部贴近身体。',
    commonErrors: '利用腰部晃动；耸肩。',
    repRange: '6-10',
  },
  {
    id: 'shrugs',
    name: 'Dumbbell Shrugs',
    nameCn: '哑铃耸肩',
    primaryMuscle: 'Traps',
    secondaryMuscles: ['Upper Back'],
    equipment: 'Dumbbells',
    type: 'isolation',
    level: 'beginner',
    instructions: '站姿双手持哑铃于体侧，耸肩尽量向上靠近耳朵，顶端停顿，缓慢下放。',
    tips: '不要旋转肩膀；保持身体直立。',
    commonErrors: '绕圈旋转肩部；借助耸肩摆动。',
    repRange: '10-15',
  },
  {
    id: 'face-pull',
    name: 'Face Pull',
    nameCn: '面拉',
    primaryMuscle: 'Rear Delts',
    secondaryMuscles: ['Upper Back', 'Traps'],
    equipment: 'Cable / Rope',
    type: 'isolation',
    level: 'beginner',
    instructions:
      '高位绳索，双手持绳对握，向后拉向面部，肘部抬高展开，肩胛后缩。',
    tips: '肘部抬至与肩同高；感受肩后束与上背收缩。',
    commonErrors: '用二头代偿；重量过大。',
    repRange: '12-20',
  },

  // ===== Arms =====
  {
    id: 'barbell-curl',
    name: 'Barbell Curl',
    nameCn: '杠铃弯举',
    primaryMuscle: 'Biceps',
    secondaryMuscles: ['Forearms'],
    equipment: 'Barbell',
    type: 'isolation',
    level: 'beginner',
    instructions: '站姿正握杠铃，大臂固定贴身，屈肘将杠铃弯起至胸前，缓慢下放。',
    tips: '大臂全程固定；避免身体后仰借力。',
    commonErrors: '甩腰借力；大臂摆动。',
    repRange: '8-12',
  },
  {
    id: 'skull-crusher',
    name: 'Skull Crusher',
    nameCn: '仰卧臂屈伸',
    primaryMuscle: 'Triceps',
    secondaryMuscles: ['Chest'],
    equipment: 'EZ Bar',
    type: 'isolation',
    level: 'intermediate',
    instructions: '仰卧，双手持EZ杠于头顶，屈肘下放至额头上方，伸肘还原。',
    tips: '大臂垂直地面固定不动，仅前臂屈伸。',
    commonErrors: '大臂随动；肘部过度外展。',
    repRange: '8-12',
  },
  {
    id: 'triceps-pushdown',
    name: 'Triceps Pushdown',
    nameCn: '绳索下压',
    primaryMuscle: 'Triceps',
    secondaryMuscles: [],
    equipment: 'Cable',
    type: 'isolation',
    level: 'beginner',
    instructions: '面对绳索站姿，大臂固定，将握把向下压至手臂伸直，控制还原。',
    tips: '大臂贴近身体固定；末端充分收缩三头。',
    commonErrors: '肘部外展；身体前压借力。',
    repRange: '10-15',
  },
  {
    id: 'hammer-curl',
    name: 'Hammer Curl',
    nameCn: '锤式弯举',
    primaryMuscle: 'Biceps',
    secondaryMuscles: ['Forearms', 'Brachialis'],
    equipment: 'Dumbbells',
    type: 'isolation',
    level: 'beginner',
    instructions: '对握哑铃（掌心相对），屈肘上弯，缓慢下放，全程大臂固定。',
    tips: '可交替进行；专注前臂转力量。',
    commonErrors: '借力摆动。',
    repRange: '10-12',
  },

  // ===== Abs =====
  {
    id: 'cable-crunch',
    name: 'Cable Crunch',
    nameCn: '绳索卷腹',
    primaryMuscle: 'Abs',
    secondaryMuscles: ['Obliques'],
    equipment: 'Cable',
    type: 'isolation',
    level: 'beginner',
    instructions: '跪姿手持高位绳索，髋部固定，弯曲脊柱向下卷腹，缓慢还原。',
    tips: '以卷曲脊柱为主而非弯腰；固定髋部。',
    commonErrors: '用髋而非腹部落动；幅度过大拉伤腰部。',
    repRange: '12-15',
  },
  {
    id: 'hanging-leg-raise',
    name: 'Hanging Leg Raise',
    nameCn: '悬垂举腿',
    primaryMuscle: 'Abs',
    secondaryMuscles: ['Hip Flexors', 'Forearms'],
    equipment: 'Pull-up Bar',
    type: 'isolation',
    level: 'advanced',
    instructions: '悬垂，核心收紧，卷曲骨盆将双腿抬起至与地面平行或更高，缓慢下放。',
    tips: '优先卷骨盆而非简单抬腿；避免摆动。',
    commonErrors: '身体前后摆动；只抬腿不卷腹。',
    repRange: '8-15',
  },
  {
    id: 'russian-twist',
    name: 'Russian Twist',
    nameCn: '俄罗斯转体',
    primaryMuscle: 'Obliques',
    secondaryMuscles: ['Abs'],
    equipment: 'Bodyweight / Plate',
    type: 'isolation',
    level: 'beginner',
    instructions: '坐姿屈膝，上身后倾，双手持重物左右转动躯干。',
    tips: '保持背部挺直；转动来自躯干而非手臂。',
    commonErrors: '含胸弓背；转幅过大。',
    repRange: '15-25',
  },

  // ===== Legs =====
  {
    id: 'squat',
    name: 'Barbell Back Squat',
    nameCn: '杠铃深蹲',
    primaryMuscle: 'Quads',
    secondaryMuscles: ['Glutes', 'Hamstrings', 'Lower Back'],
    equipment: 'Barbell / Rack',
    type: 'compound',
    level: 'intermediate',
    instructions: '杠铃置于上背，双脚与肩同宽，屈髋屈膝下蹲至大腿平行地面以下，站起。',
    tips: '膝盖与脚尖同向；核心绷紧保持脊柱中立；全程使重心在足中。',
    commonErrors: '膝盖内扣；上身前倾过度导致弓背；脚跟离地。',
    repRange: '5-8',
  },
  {
    id: 'leg-press',
    name: 'Leg Press',
    nameCn: '腿举',
    primaryMuscle: 'Quads',
    secondaryMuscles: ['Glutes', 'Hamstrings'],
    equipment: 'Machine',
    type: 'machine',
    level: 'beginner',
    instructions: '坐于腿举机，双脚踩平台与肩同宽，屈膝下放至约90°，蹬起。',
    tips: '腰部贴紧靠垫；下放过深避免骨盆后倾卷腰。',
    commonErrors: '臀部离垫卷腰；幅度过大。',
    repRange: '8-12',
  },
  {
    id: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    nameCn: '罗马尼亚硬拉',
    primaryMuscle: 'Hamstrings',
    secondaryMuscles: ['Glutes', 'Lower Back'],
    equipment: 'Barbell / Dumbbells',
    type: 'compound',
    level: 'intermediate',
    instructions:
      '站姿持杠铃，微屈膝，以屈髋为主将杠铃沿腿下放至小腿中段，感受腘绳肌拉伸，伸髋还原。',
    tips: '膝盖角度基本不变；杠铃全程贴腿；专注腘绳肌离心拉伸。',
    commonErrors: '下放过深变成深蹲；弓背。',
    repRange: '6-10',
  },
  {
    id: 'leg-curl',
    name: 'Lying Leg Curl',
    nameCn: '俯卧腿弯举',
    primaryMuscle: 'Hamstrings',
    secondaryMuscles: ['Calves'],
    equipment: 'Machine',
    type: 'isolation',
    level: 'beginner',
    instructions: '俯卧于腿弯举机，将滚轴置于脚跟上方，屈膝勾起至最大程度，控制还原。',
    tips: '髋部贴紧垫面；避免身体上抬借力。',
    commonErrors: '臀部上抬；还原过快失去张力。',
    repRange: '10-15',
  },
  {
    id: 'leg-extension',
    name: 'Leg Extension',
    nameCn: '腿屈伸',
    primaryMuscle: 'Quads',
    secondaryMuscles: [],
    equipment: 'Machine',
    type: 'isolation',
    level: 'beginner',
    instructions: '坐于腿屈伸机，将滚轴置于脚踝上方，伸膝至完全伸直，控制还原。',
    tips: '末端顶峰收缩；避免爆发甩动。',
    commonErrors: '甩动借力；还原过深拉伤膝盖。',
    repRange: '12-15',
  },
  {
    id: 'adductor-machine',
    name: 'Adductor Machine',
    nameCn: '内收机',
    primaryMuscle: 'Adductors',
    secondaryMuscles: ['Glutes'],
    equipment: 'Machine',
    type: 'isolation',
    level: 'beginner',
    instructions: '坐姿双腿外展抵住挡板，向中间夹合至最大程度，控制还原。',
    tips: '专注大腿内侧发力；幅度充分。',
    commonErrors: '爆发晃动。',
    repRange: '12-15',
  },
  {
    id: 'standing-calf-raise',
    name: 'Standing Calf Raise',
    nameCn: '站姿提踵',
    primaryMuscle: 'Calves',
    secondaryMuscles: [],
    equipment: 'Machine / Smith',
    type: 'isolation',
    level: 'beginner',
    instructions: '肩托负重站立，前脚掌踩踏板，脚跟下沉拉伸小腿，踮起至最高，顶峰停顿。',
    tips: '次数较高（12-20）感受腓肠肌；顶端停顿1秒。',
    commonErrors: '幅度不足；反弹借力。',
    repRange: '12-20',
  },
  {
    id: 'hip-thrust',
    name: 'Barbell Hip Thrust',
    nameCn: '杠铃臀推',
    primaryMuscle: 'Glutes',
    secondaryMuscles: ['Hamstrings'],
    equipment: 'Barbell / Bench',
    type: 'compound',
    level: 'intermediate',
    instructions:
      '上背靠凳，杠铃置于髋部，屈膝踩地，伸髋将臀部顶至身体成直线，顶端夹紧臀部。',
    tips: '顶端下巴微收、骨盆后倾夹臀；避免腰椎反弓。',
    commonErrors: '用腰部代偿；幅度不足。',
    repRange: '8-12',
  },

  // ===== Core of upper body =====
  {
    id: 'pull-up',
    name: 'Pull-up',
    nameCn: '引体向上',
    primaryMuscle: 'Lats',
    secondaryMuscles: ['Biceps', 'Upper Back'],
    equipment: 'Pull-up Bar',
    type: 'compound',
    level: 'intermediate',
    instructions: '正握单杠，悬垂后胸部上挺，将身体拉起至下巴过杠，控制下放。',
    tips: '从肩胛下沉启动；避免蹬腿借力；可辅助训练渐进。',
    commonErrors: '摆动借力；只用手臂拉。',
    repRange: '6-12',
  },
  {
    id: 'push-up',
    name: 'Push-up',
    nameCn: '俯卧撑',
    primaryMuscle: 'Chest',
    secondaryMuscles: ['Triceps', 'Front Delts', 'Core'],
    equipment: 'Bodyweight',
    type: 'compound',
    level: 'beginner',
    instructions: '平板支撑位，双手略宽于肩，屈肘下放至胸部接近地面，推起。',
    tips: '身体从头到脚保持直线；肘部约45°。',
    commonErrors: '塌腰；耸肩。',
    repRange: '10-20',
  },
]

export const MUSCLE_GROUPS: string[] = [
  'Chest',
  'Upper Chest',
  'Lower Chest',
  'Front Delts',
  'Side Delts',
  'Rear Delts',
  'Lats',
  'Traps',
  'Upper Back',
  'Lower Back',
  'Biceps',
  'Triceps',
  'Forearms',
  'Abs',
  'Obliques',
  'Glutes',
  'Quads',
  'Hamstrings',
  'Adductors',
  'Calves',
]

export function getExercise(id: string): Exercise | undefined {
  return EXERCISES.find((e) => e.id === id)
}

export function getExercisesByMuscle(muscle: string): Exercise[] {
  return EXERCISES.filter(
    (e) =>
      e.primaryMuscle === muscle || e.secondaryMuscles.includes(muscle),
  )
}
